# Generated by Django 4.2.9 on 2024-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.CharField(
                        help_text="识别图片的HTTP地址", max_length=512, verbose_name="img"
                    ),
                ),
                ("res", models.TextField(help_text="识别结果纯文本", verbose_name="res")),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("TITLE", "标题"),
                            ("INFO", "信息"),
                            ("QUESTION", "题目"),
                            ("HANDWRITE", "手写内容"),
                        ],
                        help_text="文本类型（标题/信息/题目/手写）",
                        max_length=512,
                        verbose_name="type",
                    ),
                ),
                (
                    "shw",
                    models.CharField(
                        help_text="加工后展示的图片HTTP地址", max_length=512, verbose_name="shw"
                    ),
                ),
            ],
        ),
    ]
