# Generated by Django 4.2.9 on 2024-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrmodel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("TITLE", "标题"),
                    ("INFO", "信息"),
                    ("QUESTION", "题目"),
                    ("HANDWRITE", "手写内容"),
                    ("OTHERS", "其它"),
                ],
                help_text="文本类型（标题/信息/题目/手写）",
                max_length=512,
                verbose_name="type",
            ),
        ),
    ]
