# Generated by Django 4.2.9 on 2024-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0002_alter_ocrmodel_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrmodel",
            name="res",
            field=models.TextField(blank=True, help_text="识别结果纯文本", verbose_name="res"),
        ),
        migrations.AlterField(
            model_name="ocrmodel",
            name="shw",
            field=models.CharField(
                blank=True,
                help_text="加工后展示的图片HTTP地址",
                max_length=512,
                verbose_name="shw",
            ),
        ),
        migrations.AlterField(
            model_name="ocrmodel",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OTHERS", "其它"),
                    ("TITLE", "标题"),
                    ("INFO", "信息"),
                    ("QUESTION", "题目"),
                    ("HANDWRITE", "手写内容"),
                ],
                default=("OTHERS", "其它"),
                help_text="文本类型（标题/信息/题目/手写）",
                max_length=512,
                verbose_name="type",
            ),
        ),
    ]
