# Generated by Django 5.0.1 on 2024-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exam_queskindname_alter_exam_examtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_kind',
            name='quesKindId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='试题类型ID'),
        ),
    ]
