# Generated by Django 5.0.3 on 2024-03-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_ques_kind_queskindid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="hasAnswers",
            field=models.IntegerField(default=0, verbose_name="上传答卷状态"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="examTimes",
            field=models.CharField(max_length=255, verbose_name="考试时间"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="paperIds",
            field=models.CharField(max_length=255, verbose_name="使用试卷"),
        ),
    ]
