# Generated by Django 5.0.3 on 2024-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_paper_hasanswers_alter_exam_examtimes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="password",
            field=models.CharField(
                default="123456", max_length=64, verbose_name="登录密码"
            ),
        ),
    ]
