# Generated by Django 5.0.3 on 2024-04-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_paper_paperstasus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="ansImg",
            field=models.TextField(verbose_name="截取内容"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="scanResult",
            field=models.TextField(verbose_name="答题结果"),
        ),
        migrations.AlterField(
            model_name="ques",
            name="quesAnswer",
            field=models.TextField(max_length=255, verbose_name="参考答案"),
        ),
        migrations.AlterField(
            model_name="ques",
            name="quesContent",
            field=models.TextField(verbose_name="题目内容"),
        ),
    ]
