# Generated by Django 5.0.3 on 2024-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_answer_ansimg_alter_answer_scanresult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="examTimes",
            field=models.TextField(verbose_name="考试时间"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="paperIds",
            field=models.TextField(verbose_name="使用试卷"),
        ),
        migrations.AlterField(
            model_name="mark",
            name="taskAllos",
            field=models.TextField(verbose_name="任务分配"),
        ),
        migrations.AlterField(
            model_name="mark_result",
            name="AIComment",
            field=models.TextField(verbose_name="AI 意见 "),
        ),
        migrations.AlterField(
            model_name="mark_result",
            name="TeacherComment",
            field=models.TextField(verbose_name="教师意见 "),
        ),
        migrations.AlterField(
            model_name="paper",
            name="quesIds",
            field=models.TextField(verbose_name="包含试题"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="quesKindIds",
            field=models.TextField(verbose_name="试卷结构 "),
        ),
        migrations.AlterField(
            model_name="paper_score_sheet",
            name="detailScores",
            field=models.TextField(verbose_name="得分详情"),
        ),
    ]
