# Generated by Django 4.2.9 on 2024-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sysId",
                    models.UUIDField(blank=True, editable=False, help_text="用户系统ID"),
                ),
                ("num", models.IntegerField(default=0, help_text="对话历史中的第几条")),
                (
                    "typ",
                    models.IntegerField(
                        default=0, help_text="信息类型 0 - AI Message / 1 - Human Message"
                    ),
                ),
                ("content", models.TextField(help_text="对话内容")),
                ("time", models.DateTimeField(auto_now_add=True, help_text="产生时间")),
            ],
        ),
    ]
