# Generated by Django 4.2.9 on 2024-02-07 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="segimg",
            name="seg_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="分割时间",
                verbose_name="time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="segimg",
            name="img",
            field=models.CharField(
                help_text="待分割的图片", max_length=512, verbose_name="img"
            ),
        ),
        migrations.AlterField(
            model_name="segimg",
            name="num",
            field=models.IntegerField(default=0, help_text="切片序列", verbose_name="num"),
        ),
    ]
