# Generated by Django 4.2.9 on 2024-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0002_segimg_seg_time_alter_segimg_img_alter_segimg_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="segimg",
            name="paper",
            field=models.CharField(
                default=None, help_text="所属试卷ID", max_length=128, verbose_name="paper"
            ),
        ),
    ]
