# Generated by Django 4.2.9 on 2024-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0003_segimg_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segimg",
            name="paper",
            field=models.CharField(
                default="None", help_text="所属试卷ID", max_length=128, verbose_name="paper"
            ),
        ),
    ]
