# Generated by Django 4.2.9 on 2024-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0007_alter_segimg_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segimg",
            name="paper",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="所属试卷ID",
                max_length=128,
                verbose_name="paper",
            ),
            preserve_default=False,
        ),
    ]
