# Generated by Django 4.2.9 on 2024-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0008_alter_segimg_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="segimg",
            name="quesId",
            field=models.IntegerField(
                blank=True, default=-1, help_text="对应题目编号", verbose_name="quesId"
            ),
        ),
        migrations.AddField(
            model_name="segimg",
            name="url",
            field=models.CharField(
                blank=True, help_text="切片地址", max_length=128, verbose_name="name"
            ),
        ),
    ]
