# Generated by Django 4.2.9 on 2024-03-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0009_segimg_quesid_segimg_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segimg",
            name="paper",
            field=models.IntegerField(
                blank=True, default=-1, help_text="所属试卷ID", verbose_name="paper"
            ),
        ),
    ]
