# Generated by Django 4.2.9 on 2024-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0011_segimg_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="segimg",
            name="certId",
            field=models.CharField(
                blank=True, help_text="所属学生准考证号", max_length=32, verbose_name="certId"
            ),
        ),
        migrations.AddField(
            model_name="segimg",
            name="stuName",
            field=models.CharField(
                blank=True, help_text="学生姓名", max_length=16, verbose_name="certId"
            ),
        ),
    ]
