# Generated by Django 4.2.9 on 2024-03-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seg", "0012_segimg_certid_segimg_stuname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segimg",
            name="paper",
            field=models.CharField(
                blank=True,
                default="unknown",
                help_text="所属试卷ID",
                max_length=128,
                verbose_name="paper",
            ),
        ),
        migrations.AlterField(
            model_name="segimg",
            name="quesId",
            field=models.CharField(
                blank=True,
                default="unknown",
                help_text="对应题目编号",
                max_length=128,
                verbose_name="quesId",
            ),
        ),
    ]
