# Generated by Django 5.0.1 on 2024-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('analyseId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='分析 ID')),
                ('examId', models.CharField(max_length=64, verbose_name='考试 ID ')),
                ('paperId', models.CharField(max_length=64, verbose_name='试卷 ID ')),
                ('quesId', models.CharField(max_length=64, verbose_name='试题 ID ')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('topScore', models.FloatField(verbose_name='最高分分数')),
                ('topStu', models.CharField(max_length=64, verbose_name='最高分考生')),
                ('botScore', models.FloatField(verbose_name='最低分分数')),
                ('botStu', models.CharField(max_length=64, verbose_name='最低分考生')),
                ('avgScore', models.FloatField(verbose_name='平均分')),
                ('modScore', models.FloatField(verbose_name='众数')),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='方差')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse_Pro',
            fields=[
                ('proId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='高级分析 ID')),
                ('requireTime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('analyseId', models.CharField(max_length=64, verbose_name='采用基本分析')),
                ('isImg', models.BooleanField(default=False, verbose_name='是否返回图片')),
                ('prompt', models.CharField(max_length=255, verbose_name='询问语句 ')),
                ('description', models.CharField(max_length=255, verbose_name='分析结果')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='答题 ID')),
                ('examId', models.CharField(max_length=64, verbose_name='考试 ID')),
                ('paperId', models.CharField(max_length=64, verbose_name='试卷 ID ')),
                ('certId', models.CharField(max_length=64, verbose_name='准考证号 ')),
                ('quesId', models.CharField(max_length=64, verbose_name='试题 ID ')),
                ('ansImg', models.CharField(max_length=255, verbose_name='截取内容')),
                ('scanResult', models.CharField(max_length=255, verbose_name='答题结果')),
            ],
        ),
        migrations.CreateModel(
            name='Certify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录 ID ')),
                ('examId', models.CharField(max_length=64, verbose_name='考试 ID ')),
                ('certId', models.CharField(blank=True, max_length=64, null=True, verbose_name='准考证号')),
                ('stuId', models.CharField(max_length=64, verbose_name='学号 ')),
                ('stuName', models.CharField(max_length=64, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='考试ID')),
                ('examName', models.CharField(max_length=64, verbose_name='考试名称')),
                ('paperIds', models.CharField(max_length=64, verbose_name='使用试卷')),
                ('examTimes', models.CharField(max_length=64, verbose_name='题型名称')),
                ('quesKindName', models.CharField(max_length=64, verbose_name='题型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('markId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='阅卷任务 ID')),
                ('examId', models.CharField(max_length=64, verbose_name='所属考试 ID')),
                ('paperId', models.CharField(max_length=64, verbose_name='所属试卷 ID')),
                ('taskAllos', models.CharField(max_length=255, verbose_name='任务分配')),
            ],
        ),
        migrations.CreateModel(
            name='Mark_result',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='记录 ID')),
                ('examId', models.CharField(max_length=64, verbose_name='考试 ID ')),
                ('paperId', models.CharField(max_length=64, verbose_name='试卷 ID')),
                ('quesId', models.CharField(max_length=64, verbose_name='试题 ID  ')),
                ('answerId', models.CharField(max_length=64, verbose_name='答卷 ID ')),
                ('markTime', models.DateTimeField(auto_now_add=True, verbose_name='批阅时间')),
                ('teaId', models.CharField(max_length=64, verbose_name='批阅教师系统 ID')),
                ('AIScore', models.FloatField(verbose_name='AI 评分')),
                ('TeacherScore', models.FloatField(verbose_name='教师评分 ')),
                ('AIComment', models.CharField(max_length=255, verbose_name='AI 意见 ')),
                ('TeacherComment', models.CharField(max_length=255, verbose_name='教师意见 ')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='试卷 ID ')),
                ('paperName', models.CharField(max_length=64, verbose_name='试卷名称')),
                ('paperFullScore', models.FloatField(verbose_name='试卷总分')),
                ('paperLevel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='全卷难度等级')),
                ('quesKindIds', models.CharField(max_length=255, verbose_name='试卷结构 ')),
                ('quesIds', models.CharField(max_length=255, verbose_name='包含试题')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Score_Sheet',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='表格 ID')),
                ('examId', models.CharField(max_length=64, verbose_name='考试 ID')),
                ('paperId', models.CharField(max_length=64, verbose_name='试卷 ID')),
                ('certId', models.CharField(max_length=64, verbose_name='准考证号')),
                ('detailScores', models.CharField(max_length=255, verbose_name='得分详情')),
                ('finalScore', models.FloatField(verbose_name='总得分')),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('quesId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='试题 ID')),
                ('quesKindId', models.IntegerField(verbose_name='题目类型')),
                ('quesContent', models.CharField(max_length=255, verbose_name='题目内容')),
                ('quesAnswer', models.CharField(max_length=255, verbose_name='参考答案')),
                ('quesDefaultScore', models.FloatField(verbose_name='默认分值')),
                ('quesLevel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='题目难度等级')),
            ],
        ),
        migrations.CreateModel(
            name='Ques_Kind',
            fields=[
                ('quesKindId', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='试题类型ID')),
                ('quesKindName', models.CharField(max_length=64, verbose_name='题型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.CharField(max_length=64, verbose_name='工号')),
                ('sysId', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='系统 ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('avatar', models.CharField(default='https://tse2-mm.cn.bing.net/th/id/OIP-C.Bb-rbUYwAPIHdXKILp7T5wHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7', max_length=255, verbose_name='头像')),
            ],
        ),
    ]
