# Generated by Django 5.0.1 on 2024-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='quesKindName',
        ),
        migrations.AlterField(
            model_name='exam',
            name='examTimes',
            field=models.CharField(max_length=64, verbose_name='考试时间'),
        ),
    ]
